# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('picture', models.ImageField(upload_to=b'')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Student')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Picture',
            },
        ),
        migrations.CreateModel(
            name='PictureGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Picture Gallery',
                'verbose_name_plural': 'Picture Galleries',
            },
        ),
        migrations.CreateModel(
            name='SubjectGallery',
            fields=[
                ('picturegallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pictures.PictureGallery')),
            ],
            options={
                'verbose_name': 'Subject Gallery',
                'verbose_name_plural': 'Subject Galleries',
            },
            bases=('pictures.picturegallery',),
        ),
        migrations.CreateModel(
            name='TopicGallery',
            fields=[
                ('subjectgallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pictures.SubjectGallery')),
            ],
            options={
                'verbose_name': 'Topic Gallery',
                'verbose_name_plural': 'Topic Galleries',
            },
            bases=('pictures.subjectgallery',),
        ),
        migrations.AddField(
            model_name='subjectgallery',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Group'),
        ),
        migrations.AddField(
            model_name='subjectgallery',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Subject'),
        ),
        migrations.CreateModel(
            name='TimetableEntryGallery',
            fields=[
                ('topicgallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pictures.TopicGallery')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.TimetableEntry')),
            ],
            options={
                'verbose_name': 'Timetable Entry Gallery',
                'verbose_name_plural': 'Timetable Entry Galleries',
            },
            bases=('pictures.topicgallery',),
        ),
        migrations.AddField(
            model_name='topicgallery',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Topic'),
        ),
    ]
