# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20161005_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='group',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='timetable_entry',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='topic',
        ),
        migrations.AddField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.TimetableEntryGallery'),
        ),
    ]
