# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20161005_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.TimetableEntryGallery'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Student'),
        ),
    ]
