# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_auto_20161024_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='depth',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
