# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0008_picturerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentrygallery',
            name='timetable_entry',
        ),
        migrations.RemoveField(
            model_name='timetableentrygallery',
            name='topicgallery_ptr',
        ),
        migrations.RemoveField(
            model_name='subjectgallery',
            name='group',
        ),
        migrations.AlterField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.SubjectGallery'),
        ),
        migrations.DeleteModel(
            name='TimetableEntryGallery',
        ),
    ]
