# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_auto_20161219_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='pictures.SubjectGallery'),
        ),
        migrations.AlterField(
            model_name='subjectgallery',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_gallery', to='education.Subject'),
        ),
    ]
