# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_auto_20161220_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgallery',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_gallery', to='education.Subject'),
        ),
    ]
