# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20161220_1549'),
        ('pictures', '0011_auto_20161220_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturerequest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Subject'),
        ),
    ]
