# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_auto_20161219_1306'),
        ('education', '0002_auto_20161005_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classday',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='classunit',
            name='days',
        ),
        migrations.RemoveField(
            model_name='classunit',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='group',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='student',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='group',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),
        migrations.DeleteModel(
            name='NonLectiveDay',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='weekly_timetable_entry',
        ),
        migrations.RemoveField(
            model_name='weeklytimetableentry',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='weeklytimetableentry',
            name='day',
        ),
        migrations.RemoveField(
            model_name='weeklytimetableentry',
            name='group',
        ),
        migrations.RemoveField(
            model_name='weeklytimetableentry',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='weeklytimetableentry',
            name='unit',
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Semester'),
        ),
        migrations.DeleteModel(
            name='ClassDay',
        ),
        migrations.DeleteModel(
            name='ClassUnit',
        ),
        migrations.DeleteModel(
            name='Enroll',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
        migrations.DeleteModel(
            name='WeeklyTimetableEntry',
        ),
    ]
