# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20161219_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
